---
- name: Set up development environment
  hosts: local
  connection: local
  gather_facts: false
  become: true
  roles:
    - common
    - bashrc
    - gitconfig
    - helm
    - terraform
    - gh
    - glab
    - uv
    - kubectl
    - k9s
    - argocd